name: Publish Catalog service image

on:
  push:
    branches:
    - main
    paths:
    - src/Services/Catalog/**

jobs:
  publish:
    name: Publish Catalog service image
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Get version
      id: get_version
      run: |
        chmod +x get_version.sh
        echo "version=$(./get_version.sh 1)" >> $GITHUB_OUTPUT
    
    - name: Login ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish catalog.api image
      run: |
        cp ./src/Services/Catalog/Catalog.API/Dockerfile .
        docker buildx build . \
          -t ghcr.io/${{ github.repository_owner }}/dotnet-microservices-catalog.api:${{ steps.get_version.outputs.version }} \
          -t ghcr.io/${{ github.repository_owner }}/dotnet-microservices-catalog.api:latest \
          --platform=linux/amd64 \
          --load
        docker push ghcr.io/${{ github.repository_owner }}/dotnet-microservices-catalog.api:${{ steps.get_version.outputs.version }}
        docker push ghcr.io/${{ github.repository_owner }}/dotnet-microservices-catalog.api:latest